project_name: "recommendation_vlm_qwen25_7b"
project_dir: "output_recommendation_vlm_qwen25_7b"
trainer: vlm_trainer

# Model Configuration
model:
  model_name_or_path: "../model/Qwen2.5-VL-7B-Instruct/"  # 更新为Qwen2.5-VL-7B
  tokenizer_name_or_path: "../model/Qwen2.5-VL-7B-Instruct/"  # 更新为Qwen2.5-VL-7B
  load_from_new: false  # Whether to load from the latest checkpoint
  lora_checkpoint_dir: "vlm_qwen25_7b_checkpoints/"  # LoRA checkpoint save path
  user_lora: true  # Whether to use LoRA
  load_in_4bit: true  # Whether to load 4-bit model
  gradient_checkpointing: true  # Enable gradient checkpointing to save GPU memory

# Dataset Configuration
datasets:
  dataset_name_or_path: "../datasets/qilin/"  # Dataset path
  train_data_processor: "VLMTrainingDataProcessor"  # Training data processor
  tokenizer_name_or_path: "../model/Qwen2.5-VL-7B-Instruct/"
  batch_size: 4  # 减小batch size以适应7B模型
  eval_batch_size: 1
  max_length: 1024  # Maximum sequence length
  negative_samples: 1  # Number of negative samples per query
  use_title: true  # Whether to use title
  use_content: true  # Whether to use content
  negative_pool: rec_result_details_with_idx
  train_data_key: recommendation_train
  use_recent_clicked_note_images: true

# Training Configuration
training:
  num_epochs: 10000  # Number of training epochs
  eval_steps: 100  # Evaluation steps
  save_steps: 100  # Save steps
  eval_epochs: 1  # Evaluate every N epochs
  save_epochs: 1  # Save model every N epochs

# Optimizer Configuration
optimizer: 
  name: Lamb 
  kwargs:
    lr: 1e-3
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1e-8

# Learning Rate Scheduler Configuration
scheduler:
  name: LinearLR
  kwargs:
    total_iters: 100

# Evaluation Configuration
evaluation:
  target_metric: "MRR@10"  # Target evaluation metric
  output_dir: "eval_results"  # Evaluation results output directory
  qrels_data_path: "../datasets/recommendation.test.qrels.csv"  # Evaluation data path
  rerank_depth: 1000  # Reranking depth
  # results_key: "bm25_results"  # Retrieved results to use
  results_key: "rec_results"  # Use XHS exposure results
  sample_num: 1000  # Number of evaluation samples, evaluate first {sample_num} samples
  test_data_key: recommendation_test

# Logger Configuration
logger:
  log_with: "tensorboard"  # Use tensorboard for training log recording
