# VLM搜索训练配置文件
# 用于训练视觉语言模型进行搜索重排序任务

# 项目基本信息
project_name: "search_vlm"                    # 项目名称，用于日志记录和模型保存
project_dir: "output_search_vlm"              # 项目输出目录，存放模型和日志

# 训练器类型选择
trainer: vlm_trainer                          # 使用VLM交叉编码器训练器

# 模型配置部分
model:
  # 基础模型路径配置
  model_name_or_path: "/data1/Qilin/baselines/model/Qwen2-VL-7B-Instruct/"  # 预训练VLM模型路径
  tokenizer_name_or_path: "/data1/Qilin/baselines/model/Qwen2-VL-7B-Instruct/"  # tokenizer路径
  
  # 训练策略配置
  load_from_new: false                        # 是否从最新checkpoint加载（false表示从头开始训练）
  lora_checkpoint_dir: "vlm_checkpoints/"     # LoRA checkpoint保存路径
  gradient_checkpointing: true                # 启用梯度检查点以节省显存
  load_in_4bit: false                         # 是否使用4bit量化加载模型
  user_lora: true                             # 是否使用LoRA微调

# 数据集配置部分
datasets:
  dataset_name_or_path: "/data1/Qilin/datasets/qilin/"  # 数据集路径
  train_data_processor: "VLMTrainingDataProcessor"      # 训练数据处理器类型
  tokenizer_name_or_path: "/data1/Qilin/baselines/model/Qwen2-VL-7B-Instruct/"  # 数据处理的tokenizer路径
  
  # 训练参数配置
  batch_size: 32                              # 批次大小（根据显存调整）
  eval_batch_size: 32                          # 评估时的批次大小
  max_length: 512                             # 最大序列长度
  negative_samples: 1                         # 每个查询的负样本数量
  
  # 数据使用配置
  use_title: true                             # 是否使用文档标题
  use_content: true                           # 是否使用文档内容

# 训练配置部分
training:
  num_epochs: 10000                           # 训练轮数（epoch数）
  eval_steps: 1000                             # 每多少步进行一次评估
  save_steps: 1000                             # 每多少步保存一次模型
  eval_epochs: 500                              # 每多少个epoch进行一次评估
  save_epochs: 500                              # 每多少个epoch保存一次模型

# 优化器配置部分
optimizer: 
  name: AdamW                                 # 优化器类型：AdamW
  kwargs:
    lr: 1e-4                                  # 学习率
    weight_decay: 0.01                        # 权重衰减
    betas: [0.9, 0.999]                       # Adam优化器的beta参数
    eps: 1e-8                                 # 数值稳定性参数

# 学习率调度器配置部分
scheduler:
  name: LinearLR                              # 学习率调度器类型：线性调度
  kwargs:
    total_iters: 100                          # 总迭代次数

# 评估配置部分
evaluation:
  target_metric: "MRR@10"                     # 目标评估指标：MRR@10（平均倒数排名）
  output_dir: "eval_results"                  # 评估结果输出目录
  qrels_data_path: "/data1/Qilin/datasets/search.test.qrels.csv"  # 评估数据路径
  rerank_depth: 1000                          # 重排序深度
  # results_key: "bm25_results"               # 使用BM25检索结果（已注释）
  results_key: "search_results"               # 使用XHS曝光结果进行重排序
  sample_num: 1000                            # 评估样本数量，评估前{sample_num}个样本

# 日志配置部分
logger:
  log_with: "tensorboard"                     # 使用tensorboard记录训练日志