# VLM性能测试配置

# 模型配置
model:
  model_name_or_path: "/data1/Qilin/baselines/model/Qwen2.5-VL-7B-Instruct/"
  device: "cuda"

# 测试配置
test:
  sample_num: 50  # 测试样本数量
  batch_size: 8    # 批处理大小
  max_candidates: 100  # 每个查询的最大候选文档数

# 评估配置
evaluation:
  metrics: ["MRR@1", "MRR@3", "MRR@5", "MRR@10", "Recall@10", "Precision@10"]
  output_dir: "vlm_test_results"

# 数据配置
data:
  dataset_path: "/data1/Qilin/datasets/qilin/"
  qrels_path: "/data1/Qilin/datasets/search.test.qrels.csv"
